// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: bike2_no_swip

#ifndef _BIKE2_NO_SWIP_UI_H
#define _BIKE2_NO_SWIP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_background;
extern lv_obj_t *ui_leftArrow;
extern lv_obj_t *ui_rightArrow;
extern lv_obj_t *ui_light;
extern lv_obj_t *ui_bittFull;
extern lv_obj_t *ui_battMid;
extern lv_obj_t *ui_battLow;
extern lv_obj_t *ui_battNone;
extern lv_obj_t *ui_batteryLevel;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_tempature;
extern lv_obj_t *ui_mileAge;
extern lv_obj_t *ui_guageNeedle;
extern lv_obj_t *ui_guageArc;
extern lv_obj_t *ui_mainSpeed;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_background_png);   // assets/background.png
LV_IMG_DECLARE( ui_img_left_arr_png);   // assets/left_arr.png
LV_IMG_DECLARE( ui_img_light_png);   // assets/light.png
LV_IMG_DECLARE( ui_img_batt_full_png);   // assets/batt_full.png
LV_IMG_DECLARE( ui_img_batt_mid_png);   // assets/batt_mid.png
LV_IMG_DECLARE( ui_img_batt_low2_png);   // assets/batt_low2.png
LV_IMG_DECLARE( ui_img_batt_low_png);   // assets/batt_low.png
LV_IMG_DECLARE( ui_img_temperature_png);   // assets/temperature.png
LV_IMG_DECLARE( ui_img_1601502596);   // assets/gauge-needle.png
LV_IMG_DECLARE( ui_img_1798728470);   // assets/gauge-indicator.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
