// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: bicycle_display

#ifndef _BICYCLE_DISPLAY_UI_H
#define _BICYCLE_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_speed;
extern lv_obj_t *ui_mileLable;
extern lv_obj_t *ui_battery;
extern lv_obj_t *ui_mileage;
extern lv_obj_t *ui_temperature;
extern lv_obj_t *ui_needle;
extern lv_obj_t *ui_needleArc;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_rightArrow;
extern lv_obj_t *ui_leftArrow;
extern lv_obj_t *ui_carLight;
extern lv_obj_t *ui_battFull;
extern lv_obj_t *ui_battMid;
extern lv_obj_t *ui_battLow;
extern lv_obj_t *ui_battNone;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_background_png);   // assets/background.png
LV_IMG_DECLARE( ui_img_1601502596);   // assets/gauge-needle.png
LV_IMG_DECLARE( ui_img_1798728470);   // assets/gauge-indicator.png
LV_IMG_DECLARE( ui_img_left_arr_png);   // assets/left_arr.png
LV_IMG_DECLARE( ui_img_light_png);   // assets/light.png
LV_IMG_DECLARE( ui_img_batt_full_png);   // assets/batt_full.png
LV_IMG_DECLARE( ui_img_batt_mid_png);   // assets/batt_mid.png
LV_IMG_DECLARE( ui_img_batt_low2_png);   // assets/batt_low2.png
LV_IMG_DECLARE( ui_img_batt_low_png);   // assets/batt_low.png
LV_IMG_DECLARE( ui_img_temperature_png);   // assets/temperature.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
