// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: bike2_no_swip

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_background = lv_img_create(ui_Screen1);
lv_img_set_src(ui_background, &ui_img_background_png);
lv_obj_set_width( ui_background, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_background, LV_SIZE_CONTENT);   /// 320
lv_obj_set_align( ui_background, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_background, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_background, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_background, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_background, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_background, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_leftArrow = lv_img_create(ui_Screen1);
lv_img_set_src(ui_leftArrow, &ui_img_left_arr_png);
lv_obj_set_width( ui_leftArrow, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_leftArrow, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_leftArrow, 85 );
lv_obj_set_y( ui_leftArrow, -130 );
lv_obj_set_align( ui_leftArrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_leftArrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_leftArrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_leftArrow,900);

ui_rightArrow = lv_img_create(ui_Screen1);
lv_img_set_src(ui_rightArrow, &ui_img_left_arr_png);
lv_obj_set_width( ui_rightArrow, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_rightArrow, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_rightArrow, 85 );
lv_obj_set_y( ui_rightArrow, 126 );
lv_obj_set_align( ui_rightArrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rightArrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_rightArrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_rightArrow,2700);

ui_light = lv_img_create(ui_Screen1);
lv_img_set_src(ui_light, &ui_img_light_png);
lv_obj_set_width( ui_light, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_light, LV_SIZE_CONTENT);   /// 41
lv_obj_set_x( ui_light, -97 );
lv_obj_set_y( ui_light, 126 );
lv_obj_set_align( ui_light, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_light, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_light, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_light,900);

ui_bittFull = lv_img_create(ui_Screen1);
lv_img_set_src(ui_bittFull, &ui_img_batt_full_png);
lv_obj_set_width( ui_bittFull, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_bittFull, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_bittFull, -100 );
lv_obj_set_y( ui_bittFull, -140 );
lv_obj_set_align( ui_bittFull, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_bittFull, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_bittFull, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_bittFull,900);

ui_battMid = lv_img_create(ui_Screen1);
lv_img_set_src(ui_battMid, &ui_img_batt_mid_png);
lv_obj_set_width( ui_battMid, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_battMid, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_battMid, -100 );
lv_obj_set_y( ui_battMid, -140 );
lv_obj_set_align( ui_battMid, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battMid, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battMid, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_battMid,900);

ui_battLow = lv_img_create(ui_Screen1);
lv_img_set_src(ui_battLow, &ui_img_batt_low2_png);
lv_obj_set_width( ui_battLow, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_battLow, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_battLow, -100 );
lv_obj_set_y( ui_battLow, -140 );
lv_obj_set_align( ui_battLow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battLow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battLow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_battLow,900);

ui_battNone = lv_img_create(ui_Screen1);
lv_img_set_src(ui_battNone, &ui_img_batt_low_png);
lv_obj_set_width( ui_battNone, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_battNone, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_battNone, -100 );
lv_obj_set_y( ui_battNone, -140 );
lv_obj_set_align( ui_battNone, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battNone, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battNone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_battNone,900);

ui_batteryLevel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_batteryLevel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryLevel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryLevel, -103 );
lv_obj_set_y( ui_batteryLevel, -107 );
lv_obj_set_align( ui_batteryLevel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryLevel,"");
lv_obj_set_style_text_color(ui_batteryLevel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batteryLevel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image8, &ui_img_temperature_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image8, -100 );
lv_obj_set_y( ui_Image8, -68 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Image8,900);

ui_tempature = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_tempature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempature, -105 );
lv_obj_set_y( ui_tempature, -42 );
lv_obj_set_align( ui_tempature, LV_ALIGN_CENTER );
lv_label_set_text(ui_tempature,"");
lv_obj_set_style_text_color(ui_tempature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mileAge = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_mileAge, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mileAge, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mileAge, -101 );
lv_obj_set_y( ui_mileAge, 65 );
lv_obj_set_align( ui_mileAge, LV_ALIGN_CENTER );
lv_label_set_text(ui_mileAge,"");
lv_obj_set_style_text_color(ui_mileAge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mileAge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_guageNeedle = lv_img_create(ui_Screen1);
lv_img_set_src(ui_guageNeedle, &ui_img_1601502596);
lv_obj_set_width( ui_guageNeedle, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_guageNeedle, LV_SIZE_CONTENT);   /// 86
lv_obj_set_x( ui_guageNeedle, -8 );
lv_obj_set_y( ui_guageNeedle, 74 );
lv_obj_set_align( ui_guageNeedle, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_guageNeedle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_guageNeedle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_guageNeedle,11,-32);
lv_img_set_angle(ui_guageNeedle,2710);

ui_guageArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_guageArc, 230);
lv_obj_set_height( ui_guageArc, 230);
lv_obj_set_x( ui_guageArc, -9 );
lv_obj_set_y( ui_guageArc, 0 );
lv_obj_set_align( ui_guageArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_guageArc, 50);
lv_arc_set_bg_angles(ui_guageArc,235,125);
lv_obj_set_style_bg_color(ui_guageArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_guageArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_guageArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_guageArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_guageArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_guageArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_guageArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_guageArc, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_guageArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_guageArc, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_guageArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( ui_guageArc, &ui_img_1798728470, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_guageArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_guageArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_mainSpeed = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_mainSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mainSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mainSpeed, -97 );
lv_obj_set_y( ui_mainSpeed, 2 );
lv_obj_set_align( ui_mainSpeed, LV_ALIGN_CENTER );
lv_label_set_text(ui_mainSpeed,"");
lv_obj_set_style_text_color(ui_mainSpeed, lv_color_hex(0x05F882), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mainSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_mainSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mainSpeed, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}
