// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: bicycle_display

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Screen1, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Screen1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_speed = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_speed, 85);
lv_obj_set_height( ui_speed, LV_SIZE_CONTENT);   /// 57
lv_obj_set_x( ui_speed, 1 );
lv_obj_set_y( ui_speed, -8 );
lv_obj_set_align( ui_speed, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_max_length(ui_speed,3);
lv_textarea_set_text(ui_speed,"23");
lv_textarea_set_one_line(ui_speed,true);
lv_obj_clear_flag( ui_speed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_speed, lv_color_hex(0x0BE75F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_speed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_speed, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_speed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_speed, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_speed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_speed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_speed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_mileLable = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_mileLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mileLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mileLable, 35 );
lv_obj_set_y( ui_mileLable, 102 );
lv_obj_set_align( ui_mileLable, LV_ALIGN_CENTER );
lv_label_set_text(ui_mileLable,"Mile");
lv_obj_set_style_text_color(ui_mileLable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mileLable, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_battery = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_battery, 65);
lv_obj_set_height( ui_battery, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_battery, -102 );
lv_obj_set_y( ui_battery, 100 );
lv_obj_set_align( ui_battery, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_battery,"100%");
lv_textarea_set_placeholder_text(ui_battery,"0%");
lv_textarea_set_one_line(ui_battery,true);
lv_obj_set_style_text_color(ui_battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_battery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_battery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_mileage = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_mileage, 60);
lv_obj_set_height( ui_mileage, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_mileage, 206 );
lv_obj_set_y( ui_mileage, 0 );
lv_obj_set_align( ui_mileage, LV_ALIGN_BOTTOM_LEFT );
lv_textarea_set_text(ui_mileage,"10km");
lv_textarea_set_placeholder_text(ui_mileage,"1km");
lv_textarea_set_one_line(ui_mileage,true);
lv_obj_set_style_text_color(ui_mileage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mileage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mileage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mileage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_mileage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_mileage, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_temperature = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_temperature, 58);
lv_obj_set_height( ui_temperature, 36);
lv_obj_set_x( ui_temperature, -42 );
lv_obj_set_y( ui_temperature, 101 );
lv_obj_set_align( ui_temperature, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_temperature,"12C");
lv_textarea_set_placeholder_text(ui_temperature,"Temp");
lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_temperature, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_temperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_temperature, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_needle = lv_img_create(ui_Screen1);
lv_img_set_src(ui_needle, &ui_img_1601502596);
lv_obj_set_width( ui_needle, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_needle, LV_SIZE_CONTENT);   /// 86
lv_obj_set_x( ui_needle, 148 );
lv_obj_set_y( ui_needle, 159 );
lv_obj_add_flag( ui_needle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_needle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_needle,11,-31);
lv_img_set_angle(ui_needle,1545);

ui_needleArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_needleArc, 230);
lv_obj_set_height( ui_needleArc, 230);
lv_obj_set_x( ui_needleArc, 0 );
lv_obj_set_y( ui_needleArc, 9 );
lv_obj_set_align( ui_needleArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_needleArc, 100);
lv_arc_set_bg_angles(ui_needleArc,145,35);
lv_obj_set_style_bg_color(ui_needleArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_needleArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor(ui_needleArc, lv_color_hex(0x4040FF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_needleArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_needleArc, lv_color_hex(0x53FF40), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_needleArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_needleArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_needleArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_needleArc, 30, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_needleArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( ui_needleArc, &ui_img_1798728470, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_needleArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_needleArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_needleArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_needleArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -88 );
lv_obj_set_y( ui_Label1, -16 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"5");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -40 );
lv_obj_set_y( ui_Label2, -73 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"10");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -74 );
lv_obj_set_y( ui_Label3, 69 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"0");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 39 );
lv_obj_set_y( ui_Label4, -73 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"15");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 85 );
lv_obj_set_y( ui_Label5, -16 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"20");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 74 );
lv_obj_set_y( ui_Label6, 63 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"25");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rightArrow = lv_img_create(ui_Screen1);
lv_img_set_src(ui_rightArrow, &ui_img_left_arr_png);
lv_obj_set_width( ui_rightArrow, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_rightArrow, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_rightArrow, 121 );
lv_obj_set_y( ui_rightArrow, -96 );
lv_obj_set_align( ui_rightArrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rightArrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_rightArrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_rightArrow,1800);

ui_leftArrow = lv_img_create(ui_Screen1);
lv_img_set_src(ui_leftArrow, &ui_img_left_arr_png);
lv_obj_set_width( ui_leftArrow, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_leftArrow, LV_SIZE_CONTENT);   /// 35
lv_obj_set_x( ui_leftArrow, -128 );
lv_obj_set_y( ui_leftArrow, -95 );
lv_obj_set_align( ui_leftArrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_leftArrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_leftArrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_carLight = lv_img_create(ui_Screen1);
lv_img_set_src(ui_carLight, &ui_img_light_png);
lv_obj_set_width( ui_carLight, LV_SIZE_CONTENT);  /// 60
lv_obj_set_height( ui_carLight, LV_SIZE_CONTENT);   /// 41
lv_obj_set_x( ui_carLight, 127 );
lv_obj_set_y( ui_carLight, 96 );
lv_obj_set_align( ui_carLight, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_carLight, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_carLight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battFull = lv_img_create(ui_Screen1);
lv_img_set_src(ui_battFull, &ui_img_batt_full_png);
lv_obj_set_width( ui_battFull, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_battFull, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_battFull, -140 );
lv_obj_set_y( ui_battFull, 98 );
lv_obj_set_align( ui_battFull, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battFull, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battFull, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battMid = lv_img_create(ui_Screen1);
lv_img_set_src(ui_battMid, &ui_img_batt_mid_png);
lv_obj_set_width( ui_battMid, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_battMid, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_battMid, -140 );
lv_obj_set_y( ui_battMid, 98 );
lv_obj_set_align( ui_battMid, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battMid, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battMid, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battLow = lv_img_create(ui_Screen1);
lv_img_set_src(ui_battLow, &ui_img_batt_low2_png);
lv_obj_set_width( ui_battLow, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_battLow, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_battLow, -140 );
lv_obj_set_y( ui_battLow, 98 );
lv_obj_set_align( ui_battLow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battLow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battLow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_battNone = lv_img_create(ui_Screen1);
lv_img_set_src(ui_battNone, &ui_img_batt_low_png);
lv_obj_set_width( ui_battNone, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_battNone, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_battNone, -140 );
lv_obj_set_y( ui_battNone, 98 );
lv_obj_set_align( ui_battNone, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_battNone, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_battNone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image5, &ui_img_temperature_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image5, -71 );
lv_obj_set_y( ui_Image5, 101 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
